
IF(LIBSSH2_REPORTED_HEADER_FOUND OR EXISTS "${LIBSSH2_INCLUDE_DIR}/libssh2.h")
	IF(NOT LIBSSH2_REPORTED_HEADER_FOUND)
		MESSAGE(STATUS "Found libssh2.h: ${LIBSSH2_INCLUDE_DIR}/libssh2.h")
		SET(LIBSSH2_REPORTED_HEADER_FOUND TRUE CACHE INTERNAL "" FORCE)
	ENDIF()
	ADD_DEFINITIONS(
		"-DLIBSSH2_LIBSSH2_H=\"${LIBSSH2_INCLUDE_DIR}/libssh2.h\""
		"-DLIBSSH2_LIBSSH2_PUBLICKEY_H=\"${LIBSSH2_INCLUDE_DIR}/libssh2_publickey.h\""
		"-DLIBSSH2_LIBSSH2_SFTP_H=\"${LIBSSH2_INCLUDE_DIR}/libssh2_sftp.h\""
	)
ENDIF()
